export const scenarioOrderByGroup = {
  iac: [
    "terraformValidateBadReference",
    "terraformModuleMissingVariable",
    "terraformModuleWrongSource",
    "terraformModuleMissingOutput",
    "terraformCheckovPublicS3",
    "terraformModuleSecurityGroup",
    "manualSecurityGroupDrift",
    "missingIamImport",
    "interruptedApplyLock",
    "terraformStateFolderMigration",
  ],
  iacSecurity: [
    "awsConfigCloudWatchRetention",
    "awsConfigS3Baseline",
    "awsConfigBlankS3SecureBucket",
    "awsConfigRdsPublicBackup",
    "awsConfigCloudTrailBaseline",
  ],
  stackOrchestration: [
    "terragruntHclfmt",
    "terragruntMissingInclude",
    "terragruntWrongSourceRef",
    "terragruntBadDependencyOutput",
  ],
  deliveryPipelines: [
    "githubActionsMissingSecret",
    "githubActionsWrongWorkingDirectory",
    "githubActionsNodeCachePath",
    "githubActionsDockerRegistryAuth",
    "githubActionsEnvironmentApproval",
    "githubActionsMatrixNodeVersion",
    "githubActionsCheckovGate",
    "githubActionsOverbroadPermissions",
    "githubActionsAwsOidcTrust",
    "jenkinsMissingCredentialsBinding",
  ],
  gitops: [
    "gitopsArgoCdTargetRevisionDrift",
    "gitopsArgoCdPruneSelfHeal",
    "gitopsFluxWrongKustomizationPath",
    "gitopsFluxSuspendedKustomization",
  ],
  linuxBasics: [
    "linuxServiceLogTriage",
  ],
  kubernetesBasics: [
    "kubernetesImagePullBackOffTriage",
    "kubernetesReadinessProbePort",
    "kubernetesHelmValuesPort",
    "kubernetesEksRbacIrsa",
  ],
  applicationSecurity: [
    "javaDependencySecretsContainerAudit",
    "javaCodeAuthSqlAudit",
  ],
  cloudSecurityAudit: [
    "awsGuardDutyCloudTrailIamAudit",
  ],
  identityAccess: [
    "iamBlankSecretsReadonly",
    "iamBlankCloudWatchLogsWrite",
    "iamS3PrefixLeastPrivilege",
    "iamDynamoDbLeadingKeys",
    "iamAzureBlobReaderScope",
    "iamGithubOidcEnvironmentTrust",
    "iamKmsEncryptionContext",
  ],
  organizationPolicy: [
    "scpDenyLeavingOrg",
    "scpBlankDenyRootUser",
    "scpBlankRequireImdsv2",
    "scpRegionRestrictionBreakGlass",
  ],
  policyAsCode: [
    "policyKyvernoRequireAppLabel",
    "policyKubernetesDefaultDenyIngress",
    "policyIstioDenyUnauthenticated",
    "policyCiliumAllowDnsEgress",
  ],
  secretsManagement: [
    "secretsSsmEnvironmentPath",
    "secretsManagerRotationKms",
    "secretsManagerResourcePolicy",
  ],
  dnsTls: [
    "dnsRoute53AlbAlias",
    "dnsAcmCloudFrontCertificate",
    "dnsAcmWildcardValidation",
  ],
  observability: [
    "observabilityLogRetention",
    "observabilityAlb5xxAlarmDimension",
    "observabilityAlarmAction",
  ],
  finops: [
    "finopsS3Lifecycle",
    "finopsNatGatewayCostSpike",
    "finopsUnattachedEbsCleanup",
  ],
  changeReview: [
    "prSecurityGroupAdminCidrReview",
    "prGithubActionsWriteAllReview",
    "prTerraformPublicS3Review",
    "prIamWildcardPolicyReview",
  ],
  networkDesign: [
    "networkingSshCidrHardening",
    "networkingSecurityGroupAlbApp",
    "networkingVpcPublicPrivateSubnets",
    "networkingVpcNatEgress",
    "networkingVpcDbIsolation",
    "networkingNaclEphemeralReturn",
    "networkingSiteToSiteVpn",
    "networkingWafAlbProtection",
    "networkingDirectConnectMultiVpc",
  ],
} as const;

export const scenarioOrder: string[] = Object.values(scenarioOrderByGroup).flat();
