export const scenarioOrderByGroup = {
  iac: [
    "terraformValidateBadReference",
    "terraformModuleMissingVariable",
    "terraformModuleWrongSource",
    "terraformModuleMissingOutput",
    "terraformCheckovPublicS3",
    "terraformModuleSecurityGroup",
    "manualSecurityGroupDrift",
    "missingIamImport",
    "interruptedApplyLock",
    "terraformStateFolderMigration",
    "terraformBlankEc2WebServer",
    "terraformBlankAzureWebApp",
    "terraformAzureBlobLeaseLock",
    "terraformAzureNsgDrift",
    "cloudFormationDriftDetection",
  ],
  iacSecurity: [
    "awsConfigCloudWatchRetention",
    "awsConfigS3Baseline",
    "awsConfigBlankS3SecureBucket",
    "awsConfigRdsPublicBackup",
    "awsConfigCloudTrailBaseline",
  ],
  stackOrchestration: [
    "terragruntHclfmt",
    "terragruntMissingInclude",
    "terragruntWrongSourceRef",
    "terragruntBadDependencyOutput",
  ],
  deliveryPipelines: [
    "githubActionsMissingSecret",
    "githubActionsWrongWorkingDirectory",
    "githubActionsNodeCachePath",
    "githubActionsDockerRegistryAuth",
    "githubActionsEnvironmentApproval",
    "githubActionsMatrixNodeVersion",
    "githubActionsCheckovGate",
    "githubActionsOverbroadPermissions",
    "githubActionsAwsOidcTrust",
    "jenkinsMissingCredentialsBinding",
    "azureDevOpsPipelineWrongVariableGroup",
    "ansiblePlaybookWrongHostGroup",
  ],
  gitops: [
    "gitopsArgoCdTargetRevisionDrift",
    "gitopsArgoCdPruneSelfHeal",
    "gitopsFluxWrongKustomizationPath",
    "gitopsFluxSuspendedKustomization",
  ],
  linuxBasics: [
    "linuxServiceLogTriage",
    "linuxDiskInodeFull",
    "linuxSystemdUnitFailed",
  ],
  kubernetesBasics: [
    "kubernetesImagePullBackOffTriage",
    "kubernetesReadinessProbePort",
    "kubernetesHelmValuesPort",
    "kubernetesMemoryLimitOom",
    "kubernetesHpaScalingPolicy",
    "kubernetesPdbNodeDrain",
    "kubernetesEksRbacIrsa",
    "kubernetesBlankDeploymentService",
    "kubernetesEksRbacWrongRules",
  ],
  applicationSecurity: [
    "semgrepBasicCommandInjection",
    "javaDependencySecretsContainerAudit",
    "containerImageCveGate",
    "javaCodeAuthSqlAudit",
    "pythonSemgrepHardcodedSecret",
    "npmTransitiveCveAudit",
  ],
  threatModeling: [
    "strideCheckoutThreatModel",
    "oidcDeploymentThreatModel",
  ],
  cloudSecurityAudit: [
    "awsGuardDutyCloudTrailIamAudit",
    "awsCloudTrailLogIntegrityAudit",
    "secHubFindingsTriageSuppress",
    "accessAnalyzerExternalFinding",
  ],
  mlops: [
    "mlopsTrainingDatasetVersion",
    "mlopsModelRegistryPromotionGate",
  ],
  identityAccess: [
    "iamBlankSecretsReadonly",
    "iamBlankCloudWatchLogsWrite",
    "iamS3PrefixLeastPrivilege",
    "iamDynamoDbLeadingKeys",
    "iamAzureBlobReaderScope",
    "iamGithubOidcEnvironmentTrust",
    "iamKmsEncryptionContext",
  ],
  organizationPolicy: [
    "scpDenyLeavingOrg",
    "scpBlankDenyRootUser",
    "scpBlankRequireImdsv2",
    "scpRegionRestrictionBreakGlass",
  ],
  policyAsCode: [
    "policyKyvernoRequireAppLabel",
    "policyKubernetesDefaultDenyIngress",
    "policyIstioDenyUnauthenticated",
    "policyCiliumAllowDnsEgress",
  ],
  secretsManagement: [
    "secretsSsmEnvironmentPath",
    "secretsManagerRotationKms",
    "secretsManagerResourcePolicy",
    "secretsVaultKvPolicyPath",
  ],
  dnsTls: [
    "dnsRoute53AlbAlias",
    "dnsAcmCloudFrontCertificate",
    "dnsAcmWildcardValidation",
  ],
  observability: [
    "observabilityLogRetention",
    "observabilityAlb5xxAlarmDimension",
    "observabilityAlarmAction",
    "observabilityPrometheusScrapeTarget",
    "observabilityOtelExporterEndpoint",
    "observabilityKafkaConsumerLag",
  ],
  finops: [
    "finopsS3Lifecycle",
    "finopsNatGatewayCostSpike",
    "finopsUnattachedEbsCleanup",
  ],
  changeReview: [
    "prSecurityGroupAdminCidrReview",
    "prGithubActionsWriteAllReview",
    "prTerraformPublicS3Review",
    "prIamWildcardPolicyReview",
  ],
  networkDesign: [
    "networkingSshCidrHardening",
    "networkingSecurityGroupAlbApp",
    "networkingVpcPublicPrivateSubnets",
    "networkingVpcNatEgress",
    "networkingVpcDbIsolation",
    "networkingNaclEphemeralReturn",
    "networkingSiteToSiteVpn",
    "networkingWafAlbProtection",
    "networkingDirectConnectMultiVpc",
  ],
  incidentResponse: [
    "incidentSev1CommandTriage",
    "incidentPostmortemBlameless",
    "incidentRunbookExecutionGap",
    "incidentAlertStormTriage",
    "incidentCustomerFacingCommsDraft",
  ],
  disasterRecovery: [
    "drRdsFailoverVerify",
    "drRegionFailoverDrill",
    "drBackupRestoreIntegrity",
    "drRpoRtoCalculation",
    "drCrossRegionReplicationLag",
  ],
  databaseOps: [
    "dbRdsFailoverStuck",
    "dbReplicationLagSpike",
    "dbSlowQueryPlanRegression",
    "dbConnectionPoolExhaustion",
    "dbPitrRestoreToPoint",
    "dbDynamoThrottledOnHotKey",
  ],
  supplyChain: [
    "supplyChainSbomGenerationGate",
    "supplyChainCosignVerifyProvenance",
    "supplyChainSyftGrypeVulnGate",
    "supplyChainSlsaLevel3Provenance",
    "supplyChainDependencyConfusion",
  ],
  sreSlo: [
    "sreSliFormulationFromSignal",
    "sreErrorBudgetBurnRate",
    "sreSloTierMismatch",
    "sreToilBudgetExceeded",
    "sreAlertSloBasedReplacement",
  ],
  messaging: [
    "msgSqsDlqRedrivePolicy",
    "msgKafkaConsumerRebalanceStorm",
    "msgSnsFanoutFilterPolicy",
    "msgOrderedDeliveryPartitionKey",
    "msgIdempotencyDuplicateConsume",
  ],
} as const;

export const scenarioOrder: string[] = Object.values(scenarioOrderByGroup).flat();
